name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py36-cover (ubuntu/x86_64)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py36-cover (windows/AMD64)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py36-cover (macos/x86_64)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py36-nocov (ubuntu/x86_64/manylinux)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp36-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py36-nocov (ubuntu/x86_64/musllinux)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp36-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py36-nocov (ubuntu/aarch64/manylinux)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp36-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py36-nocov (ubuntu/aarch64/musllinux)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp36-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py36-nocov (windows/AMD64)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'AMD64'
            cibw_build: 'cp36-*'
            os: 'windows-latest'
          - name: 'py36-nocov (windows/x86)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x86'
            tox_env: 'py36-nocov'
            cibw_arch: 'x86'
            cibw_build: 'cp36-*'
            os: 'windows-latest'
          - name: 'py36-nocov (macos/x86_64)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp36-*'
            os: 'macos-latest'
          - name: 'py37-cover (ubuntu/x86_64)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py37-cover (windows/AMD64)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py37-cover (macos/x86_64)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py37-nocov (ubuntu/x86_64/manylinux)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp37-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py37-nocov (ubuntu/x86_64/musllinux)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp37-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py37-nocov (ubuntu/aarch64/manylinux)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp37-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py37-nocov (ubuntu/aarch64/musllinux)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp37-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py37-nocov (windows/AMD64)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'AMD64'
            cibw_build: 'cp37-*'
            os: 'windows-latest'
          - name: 'py37-nocov (windows/x86)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x86'
            tox_env: 'py37-nocov'
            cibw_arch: 'x86'
            cibw_build: 'cp37-*'
            os: 'windows-latest'
          - name: 'py37-nocov (macos/x86_64)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp37-*'
            os: 'macos-latest'
          - name: 'py38-cover (ubuntu/x86_64)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py38-cover (windows/AMD64)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py38-cover (macos/x86_64)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py38-nocov (ubuntu/x86_64/manylinux)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp38-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py38-nocov (ubuntu/x86_64/musllinux)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp38-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py38-nocov (ubuntu/aarch64/manylinux)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp38-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py38-nocov (ubuntu/aarch64/musllinux)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp38-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py38-nocov (windows/AMD64)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'AMD64'
            cibw_build: 'cp38-*'
            os: 'windows-latest'
          - name: 'py38-nocov (windows/x86)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x86'
            tox_env: 'py38-nocov'
            cibw_arch: 'x86'
            cibw_build: 'cp38-*'
            os: 'windows-latest'
          - name: 'py38-nocov (macos/x86_64)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp38-*'
            os: 'macos-latest'
          - name: 'py39-cover (ubuntu/x86_64)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'py39-cover (windows/AMD64)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'py39-cover (macos/x86_64)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'py39-nocov (ubuntu/x86_64/manylinux)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp39-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py39-nocov (ubuntu/x86_64/musllinux)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp39-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py39-nocov (ubuntu/aarch64/manylinux)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp39-*manylinux*'
            os: 'ubuntu-latest'
          - name: 'py39-nocov (ubuntu/aarch64/musllinux)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'aarch64'
            cibw_build: 'cp39-*musllinux*'
            os: 'ubuntu-latest'
          - name: 'py39-nocov (windows/AMD64)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'AMD64'
            cibw_build: 'cp39-*'
            os: 'windows-latest'
          - name: 'py39-nocov (windows/x86)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x86'
            tox_env: 'py39-nocov'
            cibw_arch: 'x86'
            cibw_build: 'cp39-*'
            os: 'windows-latest'
          - name: 'py39-nocov (macos/x86_64)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-nocov'
            cibw_arch: 'x86_64'
            cibw_build: 'cp39-*'
            os: 'macos-latest'
          - name: 'pypy3-cover (ubuntu/x86_64)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy3-cover (windows/AMD64)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-cover,codecov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy3-cover (macos/x86_64)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-cover,codecov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
          - name: 'pypy3-nocov (ubuntu/x86_64/manylinux)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-nocov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'ubuntu-latest'
          - name: 'pypy3-nocov (windows/AMD64)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-nocov'
            cibw_arch: 'AMD64'
            cibw_build: false
            os: 'windows-latest'
          - name: 'pypy3-nocov (macos/x86_64)'
            python: 'pypy-3.'
            toxpython: 'pypy3.'
            python_arch: 'x64'
            tox_env: 'pypy3-nocov'
            cibw_arch: 'x86_64'
            cibw_build: false
            os: 'macos-latest'
    steps:
    - uses: docker/setup-qemu-action@v1
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off cibuildwheel -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
        CIBW_ARCHS: '${{ matrix.cibw_arch }}'
        CIBW_BUILD: '${{ matrix.cibw_build }}'
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -v
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e ${{ matrix.tox_env }} -v
    - name: regular build and test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      if: >
        !matrix.cibw_build
      run: >
        tox -e ${{ matrix.tox_env }} -v
    - name: check wheel
      if: matrix.cibw_build
      run: twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v2
      if: matrix.cibw_build
      with:
        path: wheelhouse/*.whl
